# Generated by Django 5.1 on 2024-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerimage",
            name="allocated_port_range",
        ),
        migrations.AddField(
            model_name="dockerimage",
            name="allocated_port_end",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dockerimage",
            name="allocated_port_start",
            field=models.IntegerField(default=0),
        ),
    ]
