# Generated by Django 5.1 on 2024-08-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_remove_dockercontainer_allocated_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DockerContainers',
            new_name='DockerContainer',
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
