# Generated by Django 5.1 on 2024-08-27 16:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_dockercontainer_is_killed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="magic_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
