# Generated by Django 5.1 on 2024-10-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_email_user_magic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='flag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
