# Generated by Django 5.1 on 2024-10-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dockerimage_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainer',
            name='flag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
